# Generated by Django 5.2.4 on 2026-03-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField()),
                ('total_bookings', models.IntegerField()),
                ('total_payments', models.FloatField()),
                ('total_emergencies', models.IntegerField()),
                ('report_date', models.DateField()),
                ('generated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('experience_years', models.IntegerField()),
                ('service_charge', models.FloatField()),
                ('availability_status', models.BooleanField()),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('experience_years', models.IntegerField()),
                ('consultation_fee', models.FloatField()),
                ('is_available', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('approval_status', models.CharField(max_length=50)),
                ('approval_date', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
