# Generated by Django 5.2.4 on 2026-03-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='availability_status',
            field=models.CharField(max_length=100),
        ),
    ]
