# Generated by Django 5.2.4 on 2026-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_caretaker_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.FileField(default=1, upload_to='doctor_image'),
            preserve_default=False,
        ),
    ]
