# Generated by Django 5.2.4 on 2026-04-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='image',
            field=models.FileField(default=1, upload_to='caretaker_image'),
            preserve_default=False,
        ),
    ]
