# Generated by Django 5.2.4 on 2026-05-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_caretaker_user_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
