# Generated by Django 5.2.4 on 2026-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_booking_elderprofile_emergencyalert_healthrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('doctor', 'Doctor'), ('caretaker', 'Caretaker')], default='user', max_length=10),
        ),
    ]
